### ISSUE TITLE
Wijkanders restaurant does not work

### ISSUE THREAD

**Issue by Jassob** [dtekcth/mat-chalmers#10]
We can no longer scrape the menu from Wijkanders, because the page probably has changed recently. Or maybe the menu page is hand written, it at least contains enough inconsistencies that it could be the case.

The main problem is not that we cannot scrape the page though, but that mat-chalmers don't expect it to fail. If we make it more robust and fault-tolerant we could provide a link to Wijkanders page when we fail to parse their stuff.

**Comment by adamse** [comment]
Seems that the issue is that `Text.init` errors on empty texts. Replace with `Text.dropEnd 1` and return a `Nothing` if there is no text.

Relavant line is https://github.com/adamse/mat-chalmers/blob/master/src/M/Wijkanders.hs#L46
