### ISSUE TITLE
RIP API

### ISSUE THREAD

**Issue by HenrikssonErik** [dtekcth/mat-chalmers#108]
The api is no more?

**Comment by Rembane** [comment]
RIP indeed. F in chat. Let's find out if it's dead or just resting on a
Hackkväll.

Den tis 4 okt. 2022 07:46HenrikssonErik ***@***.***> skrev:

**Comment by Rembane** [comment]
I think @The1Penguin et al took care of this. Otherwise, please reopen the issue.
