### ISSUE TITLE
Update mat-chalmers to work with the new api

### ISSUE THREAD

**Issue by Jassob** [dtekcth/mat-chalmers#11]
The old feeds are no longer working as Chalmerskonferens (the company that runs the restaurants for the Student Union) has created a public JSON [api](https://chalmerskonferens.se/api) for their menues. The api also includes information like allergens and price.

It should be easy to just use Aeson and parse the json data.

**Comment by adamse** [comment]
Please also delete the old Karen code when this works!

**Comment by Jassob** [comment]
Of course

On Wed, Aug 9, 2017, 13:09 Adam Sandberg Eriksson <notifications@github.com<mailto:notifications@github.com>> wrote:

Please also delete the old Karen code when this works!
