### ISSUE TITLE
Wijkanders menu not displaying

### ISSUE THREAD

**Issue by gustavwilliam** [dtekcth/mat-chalmers#124]
Today's menu at Wijkanders is shown as "No lunch this day!", despite there being a lunch menu available at the linked official menu site.

It's possible that their format for presenting the information was changed.

**Comment by Rembane** [comment]
Thank you for opening an issue. 

I think the problem is solved since Wijkanders shows tomorrow's menu now at 19:41. Please reopen the ticket if Wijkanders disappear again!

**Comment by Rembane** [comment]
It seems like I forgot to close this issue... lets try this again.
