### ISSUE TITLE
Wijkanders and Linsen shows menu for wrong date.

### ISSUE THREAD

**Issue by lindhe** [dtekcth/mat-chalmers#15]
The menu for Linsen (meat dish) is incorrect 2017-08-18.

![screenshot from 2017-08-18 13-07-28](https://user-images.githubusercontent.com/7773090/29456666-0b2bb530-8417-11e7-9fa3-fc428b22b05d.png)

![photo_2017-08-18_13-15-06](https://user-images.githubusercontent.com/7773090/29456702-4540189c-8417-11e7-8cd8-0c0e6045e4d6.jpg)

**Comment by lindhe** [comment]
I believe it's incorrect again: 

> Kycklingfilé med krämig tomat- och rosmarinsås samt parmesanrostad potatis [[1]](https://mat.dtek.se/)

vs

> Lasagna al forno with tomato and basil salad [[2]](https://chalmerskonferens.se/en/lunchmenyer-johanneberg/)

It was correct again a day or two ago...

**Comment by lindhe** [comment]
I think it's on the wrong day. It's showing Mondays menu for Linsen, and yesterdays menu for Wijkanders.

**Comment by Jassob** [comment]
Thank you for the additional information! 

I will see if I can get in touch with whoever is running the https://chalmerskonferens.se/api and request them to fix the Linsen week menu (the day menu is correct).
Fixing the Wijkanders bug should be rather simple... (famous last words)

**Comment by Jassob** [comment]
Linsen is now corrected (it uses the day menu instead of the week menu, so it's not correct after 15 or whenever the system changes to tomorrow's lunches but there is already an issue, #26, about that).

Wijkanders is not correct.

**Comment by Jassob** [comment]
@adamse, @Rembane: we don't look for the date when we parse the menu from wijkanders, do we?
If not I really think we should since they include it and that would stop us from showing the lunch for Friday 24/11 on Wednesday 29/11.

**Comment by Rembane** [comment]
This is a really old issue, and the code for Wijkander's has been rewritten at least once since the issue was posted, so I hereby close this issue and hope the problem is fixed. If it isn't, please file a new issue.
