### ISSUE TITLE
Something went wrong with Kårrestaurangen

### ISSUE THREAD

**Issue by lindhe** [dtekcth/mat-chalmers#16]
I was told to put this here.

![screenshot from 2017-08-28 11-34-22](https://user-images.githubusercontent.com/7773090/29768015-e4ddbfe2-8be4-11e7-8396-301a20dc1b8d.png)

**Comment by Jassob** [comment]
I think we have fixed this issue by now, sorry for the bad feedback.

(Take a look at all the dishes we present now, actually every one that the restaurants serve :o)
