### ISSUE TITLE
Make the system send an e-mail when something goes wrong

### ISSUE THREAD

**Issue by Rembane** [dtekcth/mat-chalmers#17]
Now the user must react, this makes for interesting reported issues. 

Proposed solution: The system sends an e-mail to the developers with all needed context.

**Comment by Rembane** [comment]
If you assign me to the issue, I fix it!

**Comment by adamse** [comment]
Sounds like it would be a painful flood of emails :p

**Comment by Rembane** [comment]
That's a really good incentive to make the import+parsing-flow super stable and I want to take a shot at that. :)

**Comment by adamse** [comment]
The biggest problem is that tyou can only do so much with shit data... Men lös gärna :)

**Comment by adamse** [comment]
A first step might be to get a good sample of the datas we can expect. Maybe download the menus a couple of times a day for a week or more. Then we can talk about making the parsing better!

**Comment by Rembane** [comment]
Yes indeed, I think an essential part of the mailing is to save the data that we couldn't parse and then I can enhance the parser to be able to parse that data.

**Comment by Rembane** [comment]
New plan: 

- If parsing fails, save the data we couldn't parse in a file with a good, semi-unique name.

**Comment by Rembane** [comment]
> 15:21 < adam> annat kul att gora: lagg till option att logga inputten nar parsning fallerade till 
>               filsystemet
> 15:21 < adam> --log-failing-input=/path/to/where/to/store/stuff
> 15:21 < adam> logga med timestamps, restaurang o url
>

**Comment by Rembane** [comment]
This is fixed. Kind of. The system logs all failures but not all failure modes save good context. Closing.
