### ISSUE TITLE
Missing dishes

### ISSUE THREAD

**Issue by ErikLjungdahl** [dtekcth/mat-chalmers#18]
Kårrestaurangen has 3 salads but only 1 is showing on the site. Linsen's second dish is also missing.

**Comment by Jassob** [comment]
I'll check on it!

**Comment by Jassob** [comment]
Still checking on it!

**Comment by Jassob** [comment]
I think this is fixed by [45dddff](https://github.com/adamse/mat-chalmers/commit/45dddff746be84cd65acf174b2cbbd36dfaba037).
Closing this, please reopen if not fixed
