### ISSUE TITLE
Linsen laddas inte som den ska.

### ISSUE THREAD

**Issue by Rembane** [dtekcth/mat-chalmers#24]
Den har typ hälften så många matalternativ som den borde ha.

**Comment by Jassob** [comment]
Dessutom har den fel mat på menyn..

**Comment by Jassob** [comment]
Linsens API verkar inte funka för deras veckomeny, den bara repeterar måndagens lunch..
Så jag har bytt till dagsmenyn istället för Linsen, varför den bara visar en meny och inte båda är fortfarande lite av ett mysterium dock.

**Comment by Jassob** [comment]
Right.. Anledningen till att Linsens meny är konstig jämfört med Kårens (trots att det är samma API) är för att de inte formatterar deras menyer på samma sätt...

**Comment by Jassob** [comment]
I kårens fall finns det 5 olika recipeCategories (Classic Kött, Classic Sallad, Fisk, Sallad, Vegetarisk)
och i Linsens fall finns det 1 (Dagens)

**Comment by Jassob** [comment]
En lösning på denna och #18 skulle kunna vara att plocka ut alla menyer under varje recipeCategories, jag tror nämligen bara det är den första nu.

**Comment by Jassob** [comment]
I think this is solved now, closing the issue. 
Please reopen if not satisfied.

**Comment by Rembane** [comment]
Det ser bra ut! Vielen dank!
