### ISSUE TITLE
Linsen is broken

### ISSUE THREAD

**Issue by sumsarj** [dtekcth/mat-chalmers#28]
Doesnt show anything under linsen,

**Comment by Rembane** [comment]
@sumsarj Thank you for the error report. 

Linsen's API is indeed broken. Very broken. It throws HTTP 500 when we try to fetch the page. 

I have mailed Chalmers Konferens and hope to hearing back from them soon.

Example: http://carboncloudrestaurantapi.azurewebsites.net/api/menuscreen/getdataday?restaurantid=33

**Comment by adamse** [comment]
@Rembane any replies?

**Comment by Rembane** [comment]
@adamse None at all. I think that @Jassob has been in contact with the Linsen people and has more information.

**Comment by Rembane** [comment]
@Jassob said that Linsen will always be a bit wonky since there is one person who adds the menus and that person isn't too keen on doing so. Closing this issue.

**Comment by Jassob** [comment]
Not even https://chalmerskonferens.se/lunchmenyer-johanneberg/ can render the lunch menu for Linsen, so I guess we're out of luck for now.

There is always the possibility to parse their [PDF](http://cafelinsen.se/lunch-meny.php) of course...
