### ISSUE TITLE
Does not work for Kårresturangen

### ISSUE THREAD

**Issue by nikteg** [dtekcth/mat-chalmers#3]
New RSS-feed url: http://intern.chalmerskonferens.se/view/restaurant/karrestaurangen/Veckomeny.rss

**Comment by adamse** [comment]
Thanks, will try to fix soon :+1:

**Comment by adamse** [comment]
Relevant: http://www.chalmerskonferens.se/rss-2/

**Comment by adamse** [comment]
Fixed by #4
