### ISSUE TITLE
Linsen does not go into the future

### ISSUE THREAD

**Issue by ErikLjungdahl** [dtekcth/mat-chalmers#30]
When the site is showing tomorrow's food, Linsen is still showing today's food

**Comment by Rembane** [comment]
Thank you for your feedback. This is indeed true, since Linsen doesn't have menus for the future, only for today. But it could be much more clear on mat.dtek.se. So we'll fix this!

**Comment by Rembane** [comment]
We don't support Linsen anymore. Closing.
