### ISSUE TITLE
Wijkanders menu doesn't show up

### ISSUE THREAD

**Issue by ErikLjungdahl** [dtekcth/mat-chalmers#31]
Just says "No lunch this day!", even though todays lunch can be seen on https://wijkanders.se/restaurangen/

**Comment by Rembane** [comment]
Thank you for your report.

Wijkanders don't have a nice, well-structured API, we parse their homepage instead. So I suppose that they have changed something that makes the parser go *splergh!*. We need to fix this.

The file where the parsing happens:
https://github.com/adamse/mat-chalmers/blob/master/src/M/Wijkanders.hs

**Comment by Rembane** [comment]
I tihnk solving this issue is a good way to get comfortable with the mat-project. If anyone wants to have a go at it, you're very welcome to try.

**Comment by Rembane** [comment]
I believe this has been solved and disolved many times since this issue was created. At the moment it is solved. Closing.
