### ISSUE TITLE
Sometimes things are just crazy regarding the menu (raw data issues)

### ISSUE THREAD

**Issue by emilhem** [dtekcth/mat-chalmers#32]
Swedish:
![swedish](https://user-images.githubusercontent.com/1503789/39618065-52d79a70-4f82-11e8-8a91-9c74bdc5dc5e.png)
English:
![english](https://user-images.githubusercontent.com/1503789/39618076-5530105e-4f82-11e8-8229-f31d33b5e562.png)
mat.dtek.se:
![website](https://user-images.githubusercontent.com/1503789/39618082-584c4d0c-4f82-11e8-9487-931af306f6e8.png)
Raw data:
![raw-data](https://user-images.githubusercontent.com/1503789/39618086-59f60454-4f82-11e8-82af-8c54c3ebb68c.png)

**Comment by adamse** [comment]
Hm, bad datasource... Maybe there is a better source?

@Rembane

**Comment by Rembane** [comment]
This is interesting. We download or data from the official APi, right? I wonder where the mango comes from. Which datasources do we know about?

**Comment by adamse** [comment]
I only now of what's in the code. Perhaps there is a better place?

**Comment by Rembane** [comment]
There should at least be one more where there is mango. Or we have a race condition.

**Comment by Rembane** [comment]
Please get back to us if this problem persists. Although a possible solution is that mango is equivalent to pineapple.
