### ISSUE TITLE
Tomorrow doesn't work on last day of the month

### ISSUE THREAD

**Issue by ErikLjungdahl** [dtekcth/mat-chalmers#33]
On the last day of the month the title says "Tomorrow" but the date is still today and it's showing today's dishes. So it seems like the thing calculating tomorrow's date can't overflow into the month. e.g. today is 2018-05-31 and the title currently says: "Tomorrow / 2018-05-31"

**Comment by adamse** [comment]
Probably need `gregorianMonthsRollover` from https://hackage.haskell.org/package/thyme-0.3.5.5/docs/Data-Thyme-Calendar.html in `src/M.hs:42`.

Patches welcome :)

@Jassob @Rembane
