### ISSUE TITLE
why doesn't mat work?

### ISSUE THREAD

**Issue by Rembane** [dtekcth/mat-chalmers#37]
Because someone changed the APi from a nice, comfy REST API to a GraphQL API. So, we need to rewrite the client into something that consumes GraphQL. Enjoy! 

http://carbonatescreen.azurewebsites.net/menu/week/karrestaurangen/21f31565-5c2b-4b47-d2a1-08d558129279

Example:
![nofood](https://user-images.githubusercontent.com/1253876/47967206-332c7f00-e05b-11e8-8f8c-3809ac1eaec3.png)

**Comment by adamse** [comment]
@Rembane this works now?

**Comment by Rembane** [comment]
It does, all thanks to @Kirens . He fixed!
