### ISSUE TITLE
Move all source code to under src/

### ISSUE THREAD

**Issue by Rembane** [dtekcth/mat-chalmers#43]
The source code is now in the root directory of the project. I have a hard time remembering that `Main.hs` actually exists. Can we move all source code, so that it resides under `src/` to make it easier for me and tooling to find it?

**Comment by adamse** [comment]
It might be resanable to put Main.hs in a app/ dir. That way we still have a clear separation between library and application.

**Comment by Jassob** [comment]
I agree with @adamse, that is also the current default when creating a new Stack project. We should not break existing conventions without reason :)

**Comment by Rembane** [comment]
That sounds like a good plan.
