### ISSUE TITLE
It gets stuck...

### ISSUE THREAD

**Issue by Rembane** [dtekcth/mat-chalmers#53]
Today it's the ninth of january. The page was generated two days ago in the afternoon. For some reason it is stuck now. Lets find out why and fix it! 

- [ ] Add a timestamp when the data was last updated to the footer of the homepage.
- [ ] Log when the data is updated. 

![denlasersig](https://user-images.githubusercontent.com/1253876/50886612-2fb5cb00-13f1-11e9-9168-8eef74634e96.png)

**Comment by adamse** [comment]
It is possible that the update thread has an exception and dies but it is not propagated to the main thread. Using the async package and https://hackage.haskell.org/package/async-2.2.1/docs/Control-Concurrent-Async.html#v:race_ (or if it is concurrently_ we need, I can never remember :p) will get us proper exception handling.

**Comment by Rembane** [comment]
I believe the solution in #62 from @adamse fixed this problem. I haven't seen the problem manifest since then. Closing.
