### ISSUE TITLE
Show the fancy restaurant URL in some pleasant manner

### ISSUE THREAD

**Issue by Rembane** [dtekcth/mat-chalmers#56]
We supply all restaurants with a URL pointing to a human readable representation of the menu elsewhere. Maybe we should show this URL in some way to the user?

**Comment by adamse** [comment]
It is the ☛ icon next to the name. (It seems that linsen has the wrong link)

**Comment by Rembane** [comment]
It took me until you said it for me to see it. Can we change the icon to a link symbol and see if I understand it? :)

https://unicode-table.com/en/1F517/ <- link symbol. We probably need an icon from an icon pack for it.

**Comment by adamse** [comment]
How bout making the name+fancy unicode pointing finger the link?

**Comment by Rembane** [comment]
This has been implemented for a very long time, I can't find when for some reason. So mat has legendary features, but this isn't always reflected in the issues. :D
