### ISSUE TITLE
All of the student unions restaurants are broken

### ISSUE THREAD

**Issue by adamse** [dtekcth/mat-chalmers#6]
It seems that the same RSS should work but it doesn't. Perhaps it is as simple as a missing user agent
- http://intern.chalmerskonferens.se/view/restaurant/karrestaurangen/Veckomeny.rss?today=true
- http://www.chalmerskonferens.se/rss-2/

**Comment by adamse** [comment]
Ping @Jassob

**Comment by Jassob** [comment]
Will check on that later!

**Comment by adamse** [comment]
Possilby the addition of CDATA things to the xml broke things. Perhaps a revert to `tagsoup` would make it more resilient to future changes...

**Comment by Jassob** [comment]
Yes, the CDATA tag broke taggy.

Did we use another lib back at tagsoup?
