### ISSUE TITLE
Time out resilience

### ISSUE THREAD

**Issue by Rembane** [dtekcth/mat-chalmers#93]
Should we make the service more resilient to time outs, by for instance trying again with some delay? Where the delay is a Fibonacci sequence ([1,1,2,3,5,8]) in minutes with a cutoff or reset when we get all the menus again perhaps? 

One objection to this is that it could make everything much more complicated without really adding much value, so keep an eye on that.

Example of error message: 
```
[2019-11-28T11:01:01] Kårrestaurangen: NMHttp (HttpExceptionRequest Request {
                        host                 = "heimdallprod.azurewebsites.net"
                        port                 = 443
                        secure               = True
                        requestHeaders       = [("Content-Type","application/json")]
                        path                 = "/graphql"
                        queryString          = ""
                        method               = "POST"
                        proxy                = Nothing
                        rawBody              = False
                        redirectCount        = 10
                        responseTimeout      = ResponseTimeoutDefault
                        requestVersion       = HTTP/1.1
                      }
                       ResponseTimeout)
```

**Comment by Rembane** [comment]
I think a reasonable way to handle this is to replace the low level library `http-client` with `req` and get all the sweet bonuses from a decently modern and nice library. I'm going to try that.

**Comment by The1Penguin** [comment]
Sounds fun, good luck

**Comment by Rembane** [comment]
Thank you! :)
