### ISSUE TITLE
Wijkander's fish goes red

### ISSUE THREAD

**Issue by Rembane** [dtekcth/mat-chalmers#94]
Descriptoin of error:
![Screenshot_2019-11-29 Lunch at Chalmers](https://user-images.githubusercontent.com/1253876/69865397-5b5bd100-12a1-11ea-8b98-1ee4d7cb1db6.png)

It should not be red!

The page we scraped the data from: 
[lunchmenu.html.gz](https://github.com/dtekcth/mat-chalmers/files/3904908/lunchmenu.html.gz)

**Comment by Rembane** [comment]
[lunch.html.gz](https://github.com/dtekcth/mat-chalmers/files/3931343/lunch.html.gz)

More red fish.

**Comment by adamse** [comment]
🐟

**Comment by Rembane** [comment]
Seems to be working now. Lets reopen this if it doesn't.
