### ISSUE TITLE
I would like the menu from Linsen as well

### ISSUE THREAD

**Issue by edvinalestig** [dtekcth/mat-chalmers#97]
The menu from Linsen would be nice to have.

**Comment by Rembane** [comment]
I agree wholeheartedly. Right now Linsen's menu is a PDF which is harder to parse than the JSON/HTML we usually parse, so there's quite a bit of work to get it going, but it should be done nonetheless.

The menu: http://www.cafelinsen.se/lunch-meny.php

**Comment by adamse** [comment]
@edvinalestig happy to assist if you want to try and implement.

**Comment by AlecGower** [comment]
Linsen menu is now in HTML if this helps

https://www.cafe-linsen.se/

**Comment by The1Penguin** [comment]
Fixed with #126
